### ISSUE TITLE
Why some application logic in the UI ??

### ISSUE THREAD

**Issue by fadi-botros** [MohamedISoliman/Androiddev#1]
https://github.com/MohamedISoliman/Androiddev/blob/2b26346bad0f3bccb1a2101ec2866bebc8d9a2c0/app/src/main/java/io/github/mohamedisoliman/androiddev/ui/home/HomeViewModel.java#L45-L57

I think this could be placed in the ViewModel

In iOS, I tend to make an observable boolean in the ViewModel indicating whether it is loading or no, then observe on it from the UI directly.  I may be wrong.

**Comment by mibrahimdev** [comment]
this code is already in ViewModel `HomeViewModel` is class extending from the arch component ViewModel/AndroidViewModel.
I observe on the loading and error Observables in the HomeActivity.
