### ISSUE TITLE
There is some mix between Rx and non-functional programming in some spots

### ISSUE THREAD

**Issue by fadi-botros** [MohamedISoliman/Androiddev#3]
Like

https://github.com/MohamedISoliman/Androiddev/blob/2b26346bad0f3bccb1a2101ec2866bebc8d9a2c0/app/src/main/java/io/github/mohamedisoliman/androiddev/data/GettingTopPostsWorker.java#L24-L25

I think it maybe more Rx to make `insertTopFive` to accept an `Observable`, then you give it the `take(5)` as is, without mapping,  or wrap it in other observable using `.asObservable`, this makes more customizability, and is more Rx

**Comment by mibrahimdev** [comment]
I don't see any problem in doing this way, what I think I will change is the insertTopFive() function parameter .. otherwise the code is written in Rx ..
